spring.application.name=user-service

#using config server configuration from github
spring.config.import=optional:configserver:http://localhost:8888

# Tracing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Logging Pattern
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]

