spring.application.name=USER-SERVICE
spring.profiles.active=default
#using config server configuration from github
spring.config.import=optional:configserver:http://localhost:8085

# Circuit Breaker Configuration

resilience4j.circuitbreaker.instances.ratingHotelBreaker.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.ratingHotelBreaker.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.ratingHotelBreaker.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.ratingHotelBreaker.permitted-number-of-calls-in-half-open-state=2

resilience4j.circuitbreaker.instances.ratingHotelBreaker.sliding-window-size=10

resilience4j.circuitbreaker.instances.ratingHotelBreaker.sliding-window-type=COUNT_BASED


resilience4j.circuitbreaker.configs.default.register-health-indicator=true

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
management.health.circuitbreakers.enabled=true

#rate limiter config
resilience4j.ratelimiter.instances.userRateLimiter.limit-for-period=5

resilience4j.ratelimiter.instances.userRateLimiter.limit-refresh-period=10s

resilience4j.ratelimiter.instances.userRateLimiter.timeout-duration=1s