spring.application.name=cart-service

#using config server configuration from github
spring.config.import=optional:configserver:http://localhost:8888


# Tracing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Logging Pattern
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]


# Circuit Breaker Configuration

resilience4j.circuitbreaker.instances.productEcommerceBreaker.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.productEcommerceBreaker.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.productEcommerceBreaker.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.productEcommerceBreaker.permitted-number-of-calls-in-half-open-state=2

resilience4j.circuitbreaker.instances.productEcommerceBreaker.sliding-window-size=10

resilience4j.circuitbreaker.instances.productEcommerceBreaker.sliding-window-type=COUNT_BASED


resilience4j.circuitbreaker.configs.default.register-health-indicator=true
