spring.application.name=Redis-cache-impl

server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/redis_db
spring.datasource.username=root
spring.datasource.password=fighter

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.data.redis.host=witty-alien-124842.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAeeqAAIgcDI1M2JkOTZjYzhmNzE0YWRjOTQyY2M3MDk3N2Q1M2ZjMA
spring.data.redis.ssl.enabled=true

spring.cache.type=redis

# OPTIONAL LOGS
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG